version: "3.5"

services:
  rinha-api-01: &api
    hostname: rinha-api-01
    build:
      context: .
      dockerfile: ./rinha_api/Dockerfile
    depends_on:
      - redis
    expose:
      - "3000"
    environment:
      - API_PORT=3000
      - REDIS_URL=redis://redis:6379
    networks:
      - payment-processor
      - rinha-de-backend-rust
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "50MB"

  rinha-api-02:
    <<: *api
    hostname: rinha-api-02

  rinha-worker:
    hostname: rinha-worker
    build:
      context: .
      dockerfile: ./rinha_worker/Dockerfile
    depends_on:
      - redis
    environment:
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379
    networks:
      - payment-processor
      - rinha-de-backend-rust
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "50MB"

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rinha-api-01
      - rinha-api-02
    ports:
      - "9999:9999"
    networks:
      - payment-processor
      - rinha-de-backend-rust
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  redis:
    image: redis:7.2-alpine
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - payment-processor
      - rinha-de-backend-rust
    command: redis-server --save "" --appendonly no --maxclients 20000
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "150MB"

networks:
  payment-processor:
    external: true
  rinha-de-backend-rust:
    driver: bridge
