### Global Variables
@rinhaApiBaseUrl = http://127.0.0.1:3000

### Creates a new payment on Rinha API
POST {{rinhaApiBaseUrl}}/payments HTTP/1.1
Content-Type: application/json

{
    "correlationId": "e6b72929-f0cf-438d-9951-1e424c778d89",
    "amount": 19.90
}

### Fetches payments summary
GET {{rinhaApiBaseUrl}}/payments-summary HTTP/1.1
